//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.06 at 02:35:00 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://gencore.com/ws/schema/coordinate/0.1/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.gencore.backend.java.ws.jaxb;
