// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package com.gencore.mobile.bb;


public class GPSLocationArray {
    protected com.gencore.mobile.bb.GPSLocationType[] gpsLocations;
    
    public GPSLocationArray() {
    }
    
    public GPSLocationArray(com.gencore.mobile.bb.GPSLocationType[] gpsLocations) {
        this.gpsLocations = gpsLocations;
    }
    
    public com.gencore.mobile.bb.GPSLocationType[] getGpsLocations() {
        return gpsLocations;
    }
    
    public void setGpsLocations(com.gencore.mobile.bb.GPSLocationType[] gpsLocations) {
        this.gpsLocations = gpsLocations;
    }
}
