// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package com.gencore.mobile.bb;


public class GPSLocationType {
    protected double lattitude;
    protected double longitude;
    protected float altitude;
    protected long timestamp;
    
    public GPSLocationType() {
    }
    
    public GPSLocationType(double lattitude, double longitude, float altitude, long timestamp) {
        this.lattitude = lattitude;
        this.longitude = longitude;
        this.altitude = altitude;
        this.timestamp = timestamp;
    }
    
    public double getLattitude() {
        return lattitude;
    }
    
    public void setLattitude(double lattitude) {
        this.lattitude = lattitude;
    }
    
    public double getLongitude() {
        return longitude;
    }
    
    public void setLongitude(double longitude) {
        this.longitude = longitude;
    }
    
    public float getAltitude() {
        return altitude;
    }
    
    public void setAltitude(float altitude) {
        this.altitude = altitude;
    }
    
    public long getTimestamp() {
        return timestamp;
    }
    
    public void setTimestamp(long timestamp) {
        this.timestamp = timestamp;
    }
}
