// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package com.gencore.mobile.bb;


public class RegisterDeviceResponse {
    protected int status;
    
    public RegisterDeviceResponse() {
    }
    
    public RegisterDeviceResponse(int status) {
        this.status = status;
    }
    
    public int getStatus() {
        return status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
}
