// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package com.gencore.mobile.bb;


public class SendGPSLocationRequest {
    protected java.lang.String imei;
    protected com.gencore.mobile.bb.GPSLocationType gpsLocation;
    
    public SendGPSLocationRequest() {
    }
    
    public SendGPSLocationRequest(java.lang.String imei, com.gencore.mobile.bb.GPSLocationType gpsLocation) {
        this.imei = imei;
        this.gpsLocation = gpsLocation;
    }
    
    public java.lang.String getImei() {
        return imei;
    }
    
    public void setImei(java.lang.String imei) {
        this.imei = imei;
    }
    
    public com.gencore.mobile.bb.GPSLocationType getGpsLocation() {
        return gpsLocation;
    }
    
    public void setGpsLocation(com.gencore.mobile.bb.GPSLocationType gpsLocation) {
        this.gpsLocation = gpsLocation;
    }
}
