// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package com.gencore.mobile.bb;


public class StartTrackingRequest {
    protected long startDate;
    protected java.lang.String imei;
    
    public StartTrackingRequest() {
    }
    
    public StartTrackingRequest(long startDate, java.lang.String imei) {
        this.startDate = startDate;
        this.imei = imei;
    }
    
    public long getStartDate() {
        return startDate;
    }
    
    public void setStartDate(long startDate) {
        this.startDate = startDate;
    }
    
    public java.lang.String getImei() {
        return imei;
    }
    
    public void setImei(java.lang.String imei) {
        this.imei = imei;
    }
}
