// This class was generated by 172 StubGenerator.
// Contents subject to change without notice.
// @generated

package com.gencore.mobile.bb;

public interface GPSTrackingService extends java.rmi.Remote {
	public void sendGPSLocation(java.lang.String imei, com.gencore.mobile.bb.GPSLocationType gpsLocation) throws java.rmi.RemoteException;

	public int registerDevice(java.lang.String username, java.lang.String password, java.lang.String imei) throws java.rmi.RemoteException;

	public com.gencore.mobile.bb.StartTrackingResponse startTracking(long startDate, java.lang.String imei) throws java.rmi.RemoteException;

	public com.gencore.mobile.bb.StopTrackingResponse stopTracking(java.lang.String runId, java.lang.Long endDate, java.lang.String imei, com.gencore.mobile.bb.GPSLocationArray gpsLocations) throws java.rmi.RemoteException;

}
