// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package com.gencore.mobile.bb;


public class StopTrackingRequest {
    protected java.lang.String runId;
    protected java.lang.Long endDate;
    protected java.lang.String imei;
    protected com.gencore.mobile.bb.GPSLocationArray gpsLocations;
    
    public StopTrackingRequest() {
    }
    
    public StopTrackingRequest(java.lang.String runId, java.lang.Long endDate, java.lang.String imei, com.gencore.mobile.bb.GPSLocationArray gpsLocations) {
        this.runId = runId;
        this.endDate = endDate;
        this.imei = imei;
        this.gpsLocations = gpsLocations;
    }
    
    public java.lang.String getRunId() {
        return runId;
    }
    
    public void setRunId(java.lang.String runId) {
        this.runId = runId;
    }
    
    public java.lang.Long getEndDate() {
        return endDate;
    }
    
    public void setEndDate(java.lang.Long endDate) {
        this.endDate = endDate;
    }
    
    public java.lang.String getImei() {
        return imei;
    }
    
    public void setImei(java.lang.String imei) {
        this.imei = imei;
    }
    
    public com.gencore.mobile.bb.GPSLocationArray getGpsLocations() {
        return gpsLocations;
    }
    
    public void setGpsLocations(com.gencore.mobile.bb.GPSLocationArray gpsLocations) {
        this.gpsLocations = gpsLocations;
    }
}
